// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

func Use(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Dag:          newDag(db),
		DagInstance:  newDagInstance(db),
		Task:         newTask(db),
		TaskInstance: newTaskInstance(db),
	}
}

type Query struct {
	db *gorm.DB

	Dag          dag
	DagInstance  dagInstance
	Task         task
	TaskInstance taskInstance
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Dag:          q.Dag.clone(db),
		DagInstance:  q.DagInstance.clone(db),
		Task:         q.Task.clone(db),
		TaskInstance: q.TaskInstance.clone(db),
	}
}

type queryCtx struct {
	Dag          dagDo
	DagInstance  dagInstanceDo
	Task         taskDo
	TaskInstance taskInstanceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Dag:          *q.Dag.WithContext(ctx),
		DagInstance:  *q.DagInstance.WithContext(ctx),
		Task:         *q.Task.WithContext(ctx),
		TaskInstance: *q.TaskInstance.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
