// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDag = "dag"

// Dag mapped from table <dag>
type Dag struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       string    `gorm:"column:uid;not null" json:"uid"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Desc      *string   `gorm:"column:desc" json:"desc"`
	Cron      *string   `gorm:"column:cron" json:"cron"`
	Vars      *string   `gorm:"column:vars" json:"vars"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Dag's table name
func (*Dag) TableName() string {
	return TableNameDag
}
