// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDagInstance = "dag_instance"

// DagInstance mapped from table <dag_instance>
type DagInstance struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       string    `gorm:"column:uid;not null" json:"uid"`
	DagUID    string    `gorm:"column:dag_uid;not null" json:"dag_uid"`
	Trigger   string    `gorm:"column:trigger;not null" json:"trigger"`
	Worker    string    `gorm:"column:worker;not null" json:"worker"`
	Vars      *string   `gorm:"column:vars" json:"vars"`
	Status    string    `gorm:"column:status;not null" json:"status"`
	Reason    *string   `gorm:"column:reason" json:"reason"`
	Cmd       *string   `gorm:"column:cmd" json:"cmd"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName DagInstance's table name
func (*DagInstance) TableName() string {
	return TableNameDagInstance
}
