// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskInstance = "task_instance"

// TaskInstance mapped from table <task_instance>
type TaskInstance struct {
	ID             int32   `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID            string  `gorm:"column:uid;type:varchar(255);not null" json:"uid"`
	TaskUID        string  `gorm:"column:task_uid;type:varchar(255);not null" json:"task_uid"`
	DagInstanceUID string  `gorm:"column:dag_instance_uid;type:varchar(255);not null" json:"dag_instance_uid"`
	Name           string  `gorm:"column:name;type:varchar(255);not null" json:"name"`
	ActionName     *string `gorm:"column:action_name;type:varchar(255)" json:"action_name"`
	TimeoutSecs    *int32  `gorm:"column:timeout_secs;type:int(11)" json:"timeout_secs"`
	Params         *string `gorm:"column:params;type:text" json:"params"`
	Status         *string `gorm:"column:status;type:varchar(255)" json:"status"`
	Reason         *string `gorm:"column:reason;type:varchar(255)" json:"reason"`
	Precheck       *string `gorm:"column:precheck;type:text" json:"precheck"`
}

// TableName TaskInstance's table name
func (*TaskInstance) TableName() string {
	return TableNameTaskInstance
}
