// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "task"

// Task mapped from table <task>
type Task struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID         string  `gorm:"column:uid;not null" json:"uid"`
	DagUID      string  `gorm:"column:dag_uid;not null" json:"dag_uid"`
	Name        string  `gorm:"column:name;not null" json:"name"`
	ActionName  string  `gorm:"column:action_name;not null" json:"action_name"`
	TimeoutSecs *int32  `gorm:"column:timeout_secs" json:"timeout_secs"`
	Params      *string `gorm:"column:params" json:"params"`
	Prechecks   *string `gorm:"column:prechecks" json:"prechecks"`
	DependOn    *string `gorm:"column:depend_on" json:"depend_on"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
